# Generated by Django 3.0 on 2019-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_age',
            field=models.IntegerField(db_column='age', default=18),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(db_column='name', max_length=16, unique=True),
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
